### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pacman2108**

### CODE REVIEW

**Comment by androidacy-user** [comment]
@pronoy2108 Looks like we got a bot trying to generate contributions

**Comment by Mojiberus** [comment]
@androidacybot Ладно

**Comment by sudo-nautilus** [comment]
@Mojiberus П

**Comment by sudo-nautilus** [comment]
Based bot on tg

**Comment by pacman2108** [comment]
I am not a bot

**Comment by sudo-nautilus** [comment]
Lmao :trollface:

**Pull request merged**
